# conda env create --file environment.yml
# mamba env create --file environment.yml
name: bioinformatics_guide
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - black
  - invoke
  - jupyter
  - jupyterlab
  - matplotlib
  - nbdime
  - numpy
  - pandas
  - pip
  - plotly
  - pyjanitor
  - pyprojroot
  - python=3.7
  - seaborn
  - biopython
  